info:
  build.artifact: '@project.artifactId@'
  application.version: '@project.version@'

spring:
  h2.console:
    enabled: true
    path: /console
  jpa:
    hibernate:
      format_sql: true
    show-sql: false 
      
swagger:
  config:
    apiInfo:
      title: Spotipos API
      description: Spotipos API.
      version: 1.0.0 
      termsOfServiceUrl: Jorge Filho
      contact:
        name: Jorge Filho
        url: https://github.com/jorgefilho
        email: papachristo@gmail.com
      license: https://github.com/jorgefilho/spotipos
      licenseUrl: https://github.com/jorgefilho/spotipos